name: Benchmarks

on:
  pull_request:
    branches: [ '**' ]

env:
  PROMSCALE_LOGGING: false
  PROMSCALE_BENCHMARK: true
  golang-version: 1.18.4

jobs:
  benchmark_current:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.2.1
        with:
          go-version: ${{ env.golang-version }}
        id: go

      - name: Benchmark
        run: go test -bench=. -run=^$ -benchmem -cpu=1 ./... | tee current.txt

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: current
          path: current.txt

  benchmark_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.2.1
        with:
          go-version: ${{ env.golang-version }}
        id: go

      - name: Benchmark
        run: go test -bench=. -run=^$ -benchmem -cpu=1 ./... | tee master.txt

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: master
          path: master.txt

  compare_and_publish_results:
    runs-on: ubuntu-latest
    needs: [benchmark_current, benchmark_master]
    steps:
      - name: Set up Go ${{ env.golang-version }}
        uses: actions/setup-go@v3.2.1
        with:
          go-version: ${{ env.golang-version }}
        id: go

      - name: Download result for benchmark_current
        uses: actions/download-artifact@v3
        with:
          name: current

      - name: Download result for benchmark_master
        uses: actions/download-artifact@v3
        with:
          name: master

      - name: Install benchstat
        run: go install -a golang.org/x/perf/cmd/benchstat@latest

      - name: Compare
        id: compare
        run: |
          OUTPUT=$(benchstat -delta-test=none master.txt current.txt)
          echo "${OUTPUT}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=result::$OUTPUT"

      - name: Publish results as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: compare
          message: |
            @${{ github.event.pull_request.user.login }}
            ## Benchmark Result for **${{ github.sha }}**
            ### Master vs PR
            ```
            ${{ steps.compare.outputs.result }}
            ```